version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: dashboard_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
      - ./data:/var/www/html/database/data
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/data/database.sqlite
    depends_on:
      - frontend
    networks:
      - dashboard_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: dashboard_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
      - CHOKIDAR_USEPOLLING=true
    networks:
      - dashboard_network

volumes:
  data:
    driver: local

networks:
  dashboard_network:
    driver: bridge 